////Autogenerated File - Do not edit directly

//namespace Gnosigene
//{
//    public enum HumanChromosome
//    {
//        Chromosome1 = 1,
//        Chromosome2 = 2,
//        Chromosome3 = 3,
//        Chromosome4 = 4,
//        Chromosome5 = 5,
//        Chromosome6 = 6,
//        Chromosome7 = 7,
//        Chromosome8 = 8,
//        Chromosome9 = 9,
//        Chromosome10 = 10,
//        Chromosome11 = 11,
//        Chromosome12 = 12,
//        Chromosome13 = 13,
//        Chromosome14 = 14,
//        Chromosome15 = 15,
//        Chromosome16 = 16,
//        Chromosome17 = 17,
//        Chromosome18 = 18,
//        Chromosome19 = 19,
//        Chromosome20 = 20,
//        Chromosome21 = 21,
//        Chromosome22 = 22,
//        ChromosomeMitochondria = 77,
//        ChromosomeX = 88,
//        ChromosomeY = 89,
//    }


//    public static class HumanChromosomeExtensions
//    {
//        public static string ToDisplayString(this HumanChromosome chromosome)
//        {
//            switch (chromosome)
//            {
//                case HumanChromosome.Chromosome1:
//                case HumanChromosome.Chromosome2:
//                case HumanChromosome.Chromosome3:
//                case HumanChromosome.Chromosome4:
//                case HumanChromosome.Chromosome5:
//                case HumanChromosome.Chromosome6:
//                case HumanChromosome.Chromosome7:
//                case HumanChromosome.Chromosome8:
//                case HumanChromosome.Chromosome9:
//                case HumanChromosome.Chromosome10:
//                case HumanChromosome.Chromosome11:
//                case HumanChromosome.Chromosome12:
//                case HumanChromosome.Chromosome13:
//                case HumanChromosome.Chromosome14:
//                case HumanChromosome.Chromosome15:
//                case HumanChromosome.Chromosome16:
//                case HumanChromosome.Chromosome17:
//                case HumanChromosome.Chromosome18:
//                case HumanChromosome.Chromosome19:
//                case HumanChromosome.Chromosome20:
//                case HumanChromosome.Chromosome21:
//                case HumanChromosome.Chromosome22:
//                    return ((int)chromosome).ToString();
//                case HumanChromosome.ChromosomeMitochondria:
//                    return "MT";
//                case HumanChromosome.ChromosomeX:
//                    return "X";
//                case HumanChromosome.ChromosomeY:
//                    return "Y";
//                default:
//                    return "ERROR";
//            }
//        }
//    }

//}

